### ISSUE TITLE
Push request API should return an appropriate confirmation to the caller

### ISSUE THREAD

**Issue by CLoutas** [codeburrow/hotelapp-web#5]
@PadawanTony could you have it return a confirmation in JSON format? So that the client can catch this response, and have a completion handler performing appropriate actions depending on the server's response.

**Comment by PadawanTony** [comment]
Yes, I believe so.

Let's discuss it in more detail tmrw.

**Comment by PadawanTony** [comment]
Resolved in this commit: https://github.com/codeburrow/hotelapp-web/commit/0119a603fa0db93675f478e4a0c8ed36b8d9c01c

Change code according to strict parameters for php7
